sudoL required
services:
  - docker

before_install:
  - docker build -t dprogaws/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dprogaws/react-test npm test -- --coverage

after_success:
  - docker build -t dprogaws/multi-client ./client
  - docker build -t dprogaws/multi-nginx ./nginx
  - docker build -t dprogaws/multi-server ./server
  - docker build -t dprogaws/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dprogaws/multi-client
  - docker push dprogaws/multi-nginx
  - docker push dprogaws/multi-server
  - docker push dprogaws/multi-worker